server.port=8084

app.logistica.local-url=http://localhost:8083

spring.cloud.gateway.routes[0].id=logistica-route
spring.cloud.gateway.routes[0].uri=https://servicio-logistica-latest.onrender.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/logistica/**

spring.cloud.gateway.routes[0].filters[0].name=CacheRequestBody
spring.cloud.gateway.routes[0].filters[0].args.bodyClass=java.lang.String

spring.cloud.gateway.routes[0].filters[1].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[1].args.name=logisticaCB
spring.cloud.gateway.routes[0].filters[1].args.fallbackUri=forward:/fallback/logistica
spring.cloud.gateway.routes[0].filters[1].args.statusCodes=403,500,502,503,504

resilience4j.timelimiter.instances.logisticaCB.timeoutDuration=35s

resilience4j.circuitbreaker.instances.logisticaCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.logisticaCB.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.record-exceptions=org.springframework.web.client.HttpServerErrorException