server.port=8082
spring.application.name=servicio-notificaciones
server.error.include-binding-errors=always
server.error.include-message=always

whapi.api.token=key

resend.api.key=${RESEND_API_KEY:disabled}
resend.from.email=DonaTrack <onboarding@resend.dev>

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.mvc.converters.preferred-json-mapper=jackson