spring:
  application:
    name: donatrack
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

services:
  incentivos:
    url: http://localhost:8081/incentivos
  logistica:
    url: http://localhost:8083
