server.port=8083
spring.application.name=servicio-logistica

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# --- Persistencia JPA (MySQL / TiDB) ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://gateway01.sa-east-1.prod.aws.tidbcloud.com:4000/donatrack?createDatabaseIfNotExist=true&useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Buenos_Aires}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:48EMsmYEtkL6YCy.root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:EsIfYr5esDnyXUTb}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
