server.port=8081
spring.application.name=servicio-incentivos
services.donaciones.url=http://localhost:8080
n8n.webhook.url=http://localhost:5678/webhook/nueva_insignia

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.mvc.converters.preferred-json-mapper=jackson

<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://gateway01.sa-east-1.prod.aws.tidbcloud.com:4000/donatrack?sslMode=VERIFY_IDENTITY
spring.datasource.username=48EMsmYEtkL6YCy.root
spring.datasource.password=EsIfYr5esDnyXUTb

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
=======
# --- Persistencia JPA (MySQL / TiDB) ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://gateway01.sa-east-1.prod.aws.tidbcloud.com:4000/donatrack?createDatabaseIfNotExist=true&useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Buenos_Aires}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:48EMsmYEtkL6YCy.root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:EsIfYr5esDnyXUTb}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
>>>>>>> 74fd72c (implementacion de MySQL con JPA en Servicio de incentivos y servicio de logistica)
