server.port=8081
spring.application.name=servicio-incentivos
services.donaciones.url=http://localhost:8080
n8n.webhook.url=http://localhost:5678/webhook/nueva_insignia

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.mvc.converters.preferred-json-mapper=jackson